### ISSUE TITLE
Rain falls super fast on Debian Sid

### ISSUE THREAD

**Issue by lo-yak** [nkleemann/ascii-rain#1]
Pretty much the title. I followed your instructions and it works, but it falls really, really fast. 
Is it a bug or there's a way to control the rain's speed?

**Comment by nkleemann** [comment]
The draw & update speed is controlled by a `usleep()` call here:

https://github.com/nkleemann/ascii-rain/blob/a28fe894526f6e7c126c1c793821d35ea76b17e6/rain.c#L365

It could be that `usleep` doesn't behave on your system, although that would be strange. 

Can you try increasing the frame delay in that line to test this out? Multiplying it by 10 throttles the animation speed to ~3fps, which should be noticeable.

**Comment by lo-yak** [comment]
Thanks. I set it to 80000 and now it's closer to you gif's speed :)
